format = """
<$username$hostname>\
$directory\
$git_state\
$git_branch\
$git_commit\
$git_status\
$status\
$character"""

command_timeout = 1000
add_newline = false

[username]
style_user = "blue"
style_root = "bold red"
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
disabled = false
ssh_only = false
format = "[$hostname](dimmed green)"

[directory]
style = "blue"
truncate_to_repo = true
format=" :[$path]($style) $read_only"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# [status]
# disabled = false
# format = "[$symbol]($style) "

[git_branch]
style = "bold purple"
format = "󰊢\non [$symbol$branch(:$remote_branch)]($style) "
only_attached = true

[git_commit]
tag_disabled = false
format = '''

\([$hash$tag_symbol$tag]($style)\) '''

[git_state]
style = 'bold red'
